name: kanggo_fe_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.2
  sqflite: ^2.3.0
  # sqlite3_flutter_libs: ^0.5.32
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
